# Generated by Django 4.2.11 on 2024-03-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(max_length=1000, verbose_name='School Address')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Contact Email')),
                ('website', models.CharField(max_length=255, unique=True, verbose_name='Website url')),
                ('phone_number', models.IntegerField(max_length=60, unique=True, verbose_name='Phone Number')),
            ],
        ),
    ]
