# Generated by Django 4.2.11 on 2024-03-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0002_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=models.IntegerField(max_length=60, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(max_length=255, verbose_name='Website url'),
        ),
    ]
