# Generated by Django 4.2.11 on 2024-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0003_alter_school_email_alter_school_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('benefit', models.CharField(max_length=255, verbose_name='Scholarship Benefits')),
                ('requirement', models.TextField(max_length=1000, verbose_name='Application Requirements')),
                ('link', models.CharField(max_length=255, verbose_name='Link to apply')),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
