# Generated by Django 4.2.11 on 2024-03-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0004_scholarship_alter_school_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Middle Name'),
            preserve_default=False,
        ),
    ]
