# Generated by Django 4.2.11 on 2024-03-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0006_user_current_degree_user_dob_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='requirement',
        ),
    ]
