# Generated by Django 4.2.11 on 2024-03-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0007_remove_scholarship_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='school',
            field=models.CharField(default='Naija', max_length=255, verbose_name='School'),
            preserve_default=False,
        ),
    ]
