# Generated by Django 4.2.11 on 2024-03-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0008_scholarship_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default='None', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='degrees',
            field=models.CharField(default='Bsc', max_length=600, verbose_name='Degrees Awarded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='money',
            field=models.IntegerField(default=2300, verbose_name='Amount to pay'),
            preserve_default=False,
        ),
    ]
