# Generated by Django 4.2.11 on 2024-03-29 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0009_remove_school_address_remove_school_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch_finder_api.school', verbose_name='School')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
