# Generated by Django 4.2.11 on 2024-04-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0014_rename_money_scholarship_bnefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='bnefit',
            new_name='benefit',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='school',
        ),
    ]
