# Generated by Django 4.2.11 on 2024-04-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_finder_api', '0015_rename_bnefit_scholarship_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school_images/', verbose_name='School Image'),
        ),
    ]
